/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

import Auth.FrmSingUp;
import Auth.FrmLogin;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.Cursor;

/**
 *
 * @author carlo
 */
public class FrmApp extends javax.swing.JFrame {
    
    static Color mainColor = new Color(0, 153, 255);//Usar colores rgb
    static Cursor handCurosr = new Cursor(Cursor.HAND_CURSOR);

    /**
     * Creates new form FrmApp
     */
    private String user;
    private boolean off;
    private boolean on;
    
    public FrmApp() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/control.png")));
        LblLight.setVisible(false);
        BtnCloseSesion.setVisible(false);
        handCursor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        PanelAsideMenu = new javax.swing.JPanel();
        UserImage = new javax.swing.JLabel();
        LblUserName = new javax.swing.JLabel();
        LblLight = new javax.swing.JLabel();
        LblDark = new javax.swing.JLabel();
        BtnLogIn = new javax.swing.JButton();
        BtnSingUp = new javax.swing.JButton();
        BtnCloseSesion = new javax.swing.JButton();
        PanelTopMenu = new javax.swing.JPanel();
        BtnIncio = new javax.swing.JLabel();
        BtnAvailables = new javax.swing.JLabel();
        BtnProximamente = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAsideMenu.setBackground(new java.awt.Color(0, 153, 255));
        PanelAsideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/User.png"))); // NOI18N
        PanelAsideMenu.add(UserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 17, -1, -1));

        LblUserName.setBackground(new java.awt.Color(0, 204, 255));
        LblUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblUserName.setForeground(new java.awt.Color(255, 255, 255));
        LblUserName.setText("NombreUsuario");
        PanelAsideMenu.add(LblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 129, -1, 29));

        LblLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Sunicon.png"))); // NOI18N
        LblLight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblLightMouseClicked(evt);
            }
        });
        PanelAsideMenu.add(LblLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 58));

        LblDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Moonicon.png"))); // NOI18N
        LblDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDarkMouseClicked(evt);
            }
        });
        PanelAsideMenu.add(LblDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 58));

        BtnLogIn.setBackground(new java.awt.Color(51, 102, 255));
        BtnLogIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogIn.setText("Inicar Sesion");
        BtnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogInMouseEntered(evt);
            }
        });
        BtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogInActionPerformed(evt);
            }
        });
        PanelAsideMenu.add(BtnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 40));

        BtnSingUp.setBackground(new java.awt.Color(0, 102, 255));
        BtnSingUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSingUp.setForeground(new java.awt.Color(255, 255, 255));
        BtnSingUp.setText("Registrarse");
        BtnSingUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSingUpMouseEntered(evt);
            }
        });
        BtnSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSingUpActionPerformed(evt);
            }
        });
        PanelAsideMenu.add(BtnSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 40));

        BtnCloseSesion.setBackground(new java.awt.Color(0, 102, 255));
        BtnCloseSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCloseSesion.setText("Cerrar Sesion");
        BtnCloseSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseSesionActionPerformed(evt);
            }
        });
        PanelAsideMenu.add(BtnCloseSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 40));

        PanelBackground.add(PanelAsideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 730));

        PanelTopMenu.setBackground(new java.awt.Color(0, 153, 255));
        PanelTopMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnIncio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnIncio.setForeground(new java.awt.Color(255, 255, 255));
        BtnIncio.setText("Inicio");
        PanelTopMenu.add(BtnIncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 20));

        BtnAvailables.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAvailables.setForeground(new java.awt.Color(255, 255, 255));
        BtnAvailables.setText("Disponibles");
        PanelTopMenu.add(BtnAvailables, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 110, 20));

        BtnProximamente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnProximamente.setForeground(new java.awt.Color(255, 255, 255));
        BtnProximamente.setText("Proximamente");
        PanelTopMenu.add(BtnProximamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, -1));

        TxtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        TxtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        TxtBuscar.setText("Buscar");
        TxtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtBuscarMouseClicked(evt);
            }
        });
        PanelTopMenu.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/busquedaIcon.png"))); // NOI18N
        PanelTopMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 30));

        PanelBackground.add(PanelTopMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 840, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Tienda de videojuegos hecha por un principiante");
        PanelBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 66, 580, 660));

        getContentPane().add(PanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo para que el nombre de usuario aparezca

    public void getUserName(String user) {
        this.user = user;
        LblUserName.setText(user);
    }

    public void buttonOn(boolean on) {
        this.on = on;
        BtnCloseSesion.setVisible(on);
    }

    public void buttonOff(boolean off) {
        this.off = off;
        BtnLogIn.setVisible(off);
        BtnSingUp.setVisible(off);
        
    }
    private void LblLightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLightMouseClicked
        LblLight.setVisible(false);
        LblDark.setVisible(true);
        PanelAsideMenu.setBackground(mainColor);
        PanelTopMenu.setBackground(mainColor);
        BtnSingUp.setBackground(mainColor);
        BtnLogIn.setBackground(mainColor);
        BtnCloseSesion.setBackground(mainColor);
    }//GEN-LAST:event_LblLightMouseClicked

    private void LblDarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDarkMouseClicked
        LblLight.setVisible(true);
        LblDark.setVisible(false);
        PanelAsideMenu.setBackground(Color.BLACK);
        PanelTopMenu.setBackground(Color.BLACK);
        BtnLogIn.setBackground(Color.BLACK);
        BtnSingUp.setBackground(Color.BLACK);
        BtnCloseSesion.setBackground(Color.black);
    }//GEN-LAST:event_LblDarkMouseClicked

    private void BtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogInActionPerformed
        dispose();
        FrmLogin log = new FrmLogin();
        log.setVisible(true);
    }//GEN-LAST:event_BtnLogInActionPerformed

    private void BtnSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSingUpActionPerformed
        dispose();
        FrmSingUp sing = new FrmSingUp();
        sing.setVisible(true);
    }//GEN-LAST:event_BtnSingUpActionPerformed

    private void BtnLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogInMouseEntered
        
    }//GEN-LAST:event_BtnLogInMouseEntered

    private void BtnSingUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSingUpMouseEntered
        
    }//GEN-LAST:event_BtnSingUpMouseEntered

    private void BtnCloseSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseSesionActionPerformed
        dispose();
        FrmLogin log = new FrmLogin();
        log.setVisible(true);
    }//GEN-LAST:event_BtnCloseSesionActionPerformed

    private void TxtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBuscarMouseClicked
        TxtBuscar.setText("");
        TxtBuscar.setForeground(Color.black);
    }//GEN-LAST:event_TxtBuscarMouseClicked
    
    public void handCursor() {
        BtnIncio.setCursor(handCurosr);
        BtnAvailables.setCursor(handCurosr);
        BtnProximamente.setCursor(handCurosr);
        LblDark.setCursor(handCurosr);
        LblLight.setCursor(handCurosr);
        BtnLogIn.setCursor(handCurosr);
        BtnSingUp.setCursor(handCurosr);
        BtnCloseSesion.setCursor(handCurosr);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAvailables;
    private javax.swing.JButton BtnCloseSesion;
    private javax.swing.JLabel BtnIncio;
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JLabel BtnProximamente;
    private javax.swing.JButton BtnSingUp;
    private javax.swing.JLabel LblDark;
    private javax.swing.JLabel LblLight;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JPanel PanelAsideMenu;
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JPanel PanelTopMenu;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel UserImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
