/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Auth;

import java.awt.Toolkit;
import tienda.FrmApp;
import CTXT.*;
import Models.*;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class FrmLogin extends javax.swing.JFrame {

    static ArrayList<Empleado> arrEm = new ArrayList<>();
    static ArrayList<Cliente> listCle = new ArrayList<>();
    static CCliente txtCli = new CCliente();
    static CEmpleado txtEm = new CEmpleado();
    static Cursor handCur = new Cursor(Cursor.HAND_CURSOR);

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        getTxtCliente();
        getTxtEm();
        CbxShow.setCursor(handCur);
        LblUnvisible.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/UserIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtPass = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        BtnRegistrarse = new javax.swing.JButton();
        CbxShow = new javax.swing.JCheckBox();
        LblUnvisible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 82, -1, -1));

        TxtUser.setBackground(new java.awt.Color(255, 255, 255));
        TxtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtUser.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 129, 203, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 258, -1, -1));

        TxtPass.setBackground(new java.awt.Color(255, 255, 255));
        TxtPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtPass.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(TxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 314, 203, -1));

        BtnIngresar.setBackground(new java.awt.Color(0, 51, 255));
        BtnIngresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 441, 129, 41));

        BtnRegistrarse.setBackground(new java.awt.Color(0, 51, 255));
        BtnRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 441, -1, 41));

        CbxShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/visible.png"))); // NOI18N
        CbxShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxShowMouseClicked(evt);
            }
        });
        CbxShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxShowActionPerformed(evt);
            }
        });
        jPanel1.add(CbxShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 319, 50, 30));

        LblUnvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/unvisible.png"))); // NOI18N
        jPanel1.add(LblUnvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        if (login() == true) {
            dispose();
            FrmApp app = new FrmApp();
            app.getUserName(TxtUser.getText());
            app.buttonOff(false);
            app.buttonOn(true);
            app.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Login", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed
        dispose();
        FrmSingUp sing = new FrmSingUp();
        sing.setVisible(true);
    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void CbxShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxShowMouseClicked
        showPass();
    }//GEN-LAST:event_CbxShowMouseClicked

    private void CbxShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxShowActionPerformed

    public void showPass() {
        if (CbxShow.isSelected()) {
            TxtPass.setEchoChar((char) 0);
            LblUnvisible.setVisible(true);
        } else {
            TxtPass.setEchoChar('*');
            LblUnvisible.setVisible(false);

        }
    }

    public boolean login() {
        boolean log = false;
        String pass = new String(TxtPass.getPassword());
        String username = TxtUser.getText(); // Obtener el texto del campo de usuario
        for (Cliente cli : listCle) {
            if (username.equals(cli.getNombreUsuario())) { // Comparar correctamente
                if (cli.getPassword().equals(pass)) { // Comparar con la contraseña correcta
                    log = true;
                    break; // Salir del bucle si se ha autenticado
                }
            }
        }
        return log;
    }

    public void getTxtCliente() {
        listCle = txtCli.getClienTxt();
    }

    public void getTxtEm() {
        arrEm = txtEm.getDataTxt();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JCheckBox CbxShow;
    private javax.swing.JLabel LblUnvisible;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
